ubuntu-latest do the job. check for fail log

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,17 +8,17 @@ jobs:
 
     test_app:
         name: Test app
-        runs-on: macos-latest
+        runs-on: ubuntu-latest
 
         steps:
             -   name: checkout
                 uses: actions/checkout@v4
 
-#            -   name: Enable KVM group perms
-#                run: |
-#                    echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
-#                    sudo udevadm control --reload-rules
-#                    sudo udevadm trigger --name-match=kvm
+            -   name: Enable KVM group perms
+                run: |
+                    echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+                    sudo udevadm control --reload-rules
+                    sudo udevadm trigger --name-match=kvm
 
             -   name: Set up JDK 17
                 uses: actions/setup-java@v3
@@ -82,6 +82,13 @@ jobs:
                         echo "Clean up installed apk"
                         adb uninstall com.example.githubactionapplication.test || true
                         adb uninstall com.example.githubactionapplication || true
+
+            -   name: Check for FAILURES!!!
+                run: |
+                      if grep -q "FAILURES!!!" "${{ github.workspace }}/path/to/log/file.txt"; then
+                        echo "Failures detected in the log!"
+                        exit 1
+                      fi
 
 #            -   name: Run Android instrumented tests
 #                uses: reactivecircus/android-emulator-runner@v2
